import type { Camera } from "@/types";

export const DEFAULT_CAMERAS: Camera[] = [
	{
		id: "cam1",
		brand: "Canon",
		model: "A-1",
		nickname: "",
		serial: "",
		format: "35mm",
		hasInterchangeableBack: false,
		backs: [],
	},
	{
		id: "cam2",
		brand: "Canon",
		model: "AE-1",
		nickname: "",
		serial: "",
		format: "35mm",
		hasInterchangeableBack: false,
		backs: [],
	},
	{
		id: "cam3",
		brand: "Hasselblad",
		model: "503cx",
		nickname: "",
		serial: "",
		format: "120",
		hasInterchangeableBack: true,
		backs: [
			{ id: "back1", name: "A12 — Couleur", ref: "A12" },
			{ id: "back2", name: "A12 — N&B", ref: "A12" },
		],
	},
	{
		id: "cam4",
		brand: "Yashica",
		model: "Mat 124G",
		nickname: "",
		serial: "",
		format: "120",
		hasInterchangeableBack: false,
		backs: [],
	},
	{
		id: "cam5",
		brand: "Olympus",
		model: "mju-II",
		nickname: "",
		serial: "",
		format: "35mm",
		hasInterchangeableBack: false,
		backs: [],
	},
	{
		id: "cam6",
		brand: "Canon",
		model: "1000FN",
		nickname: "",
		serial: "",
		format: "35mm",
		hasInterchangeableBack: false,
		backs: [],
	},
];
