import { DEMO_FILM_DEVELOPED } from "@/tour/demo-data";
import type { TourStep } from "@/tour/tour-types";

export const TOUR_STEPS: TourStep[] = [
	{
		id: "welcome",
		screen: "home",
		target: null,
		i18nKey: "tour.welcome",
		placement: "center",
	},
	{
		id: "dashboard-stats",
		screen: "home",
		target: '[data-tour="stat-cards"]',
		i18nKey: "tour.dashboardStats",
		placement: "bottom",
		padding: 8,
	},
	{
		id: "dashboard-equipment",
		screen: "home",
		target: '[data-tour="equipment-section"]',
		i18nKey: "tour.dashboardEquipment",
		placement: "bottom",
		padding: 8,
	},
	{
		id: "dashboard-active",
		screen: "home",
		target: '[data-tour="active-rolls"]',
		i18nKey: "tour.dashboardActive",
		placement: "top",
		padding: 8,
	},
	{
		id: "stock",
		screen: "stock",
		target: '[data-tour="stock-list"]',
		i18nKey: "tour.stock",
		placement: "top",
		padding: 8,
		delay: 250,
	},
	{
		id: "film-detail",
		screen: "filmDetail",
		selectedFilmId: DEMO_FILM_DEVELOPED,
		target: '[data-tour="film-timeline"]',
		i18nKey: "tour.filmDetail",
		placement: "top",
		padding: 8,
		delay: 250,
	},
	{
		id: "equipment",
		screen: "cameras",
		target: '[data-tour="cameras-tab"]',
		i18nKey: "tour.equipment",
		placement: "top",
		padding: 8,
		delay: 250,
	},
	{
		id: "stats",
		screen: "stats",
		target: '[data-tour="stats-overview"]',
		i18nKey: "tour.stats",
		placement: "bottom",
		padding: 8,
		delay: 250,
	},
	{
		id: "tour-end",
		screen: "home",
		target: null,
		i18nKey: "tour.tourEnd",
		placement: "center",
		delay: 250,
	},
];
