import { DEMO_FILM_DEVELOPED } from "@/tour/demo-data";
import type { TourStep } from "@/tour/tour-types";

export const TOUR_STEPS: TourStep[] = [
	{
		id: "welcome",
		screen: "home",
		target: null,
		i18nKey: "tour.welcome",
		placement: "center",
	},
	{
		id: "carnet-filters",
		screen: "home",
		target: '[data-tour="carnet-filters"]',
		i18nKey: "tour.carnetFilters",
		placement: "bottom",
		padding: 8,
		delay: 200,
	},
	{
		id: "carnet-card",
		screen: "home",
		target: '[data-tour="carnet-card"]',
		i18nKey: "tour.carnetCard",
		placement: "bottom",
		padding: 8,
		delay: 200,
	},
	{
		id: "stock",
		screen: "stock",
		target: '[data-tour="stock-list"]',
		i18nKey: "tour.stock",
		placement: "top",
		padding: 8,
		delay: 250,
	},
	{
		id: "stock-filters",
		screen: "stock",
		target: '[data-tour="stock-filters-button"]',
		i18nKey: "tour.stockFilters",
		placement: "bottom",
		padding: 8,
		delay: 200,
	},
	{
		id: "film-lifecycle",
		screen: "filmDetail",
		selectedFilmId: DEMO_FILM_DEVELOPED,
		target: '[data-tour="film-lifecycle"]',
		i18nKey: "tour.filmLifecycle",
		placement: "bottom",
		padding: 8,
		delay: 250,
	},
	{
		id: "equipment",
		screen: "cameras",
		target: '[data-tour="equipment-tabs"]',
		i18nKey: "tour.equipment",
		placement: "bottom",
		padding: 8,
		delay: 250,
	},
	{
		id: "stats",
		screen: "stats",
		target: '[data-tour="stats-overview"]',
		i18nKey: "tour.stats",
		placement: "bottom",
		padding: 8,
		delay: 250,
	},
	{
		id: "tour-end",
		screen: "home",
		target: null,
		i18nKey: "tour.tourEnd",
		placement: "center",
		delay: 250,
	},
];
